### ISSUE TITLE
Library raises `NameError` if _has_cpp_library is False

### ISSUE THREAD

**Issue by swails** [facebookresearch/xformers#1000]
# 🐛 Bug

## To Reproduce

Call `_matmul_with_mask` when `_has_cpp_library` is `False`.  [These lines show that `SparseCS` is imported only if `_has_cpp_library` is True](https://github.com/facebookresearch/xformers/blob/d5dcbb9e041fda059b167afa908bde526e668414/xformers/components/attention/core.py#L18-L19).

However, not all `assert not isinstance(thing, SparseCS)` is protected behind a `if _has_cpp_library`, leading to the following exception in one of my examples:

```python
            if (
>               not isinstance(mask, SparseCS)
                and mask.ndim == 3
                and mask.shape[0] != att.shape[0]
                and (att.shape[0] % mask.shape[0]) == 0
            ):
E           NameError: name 'SparseCS' is not defined

/venv/lib/python3.10/site-packages/xformers/components/attention/core.py:105: NameError
```

## Expected behavior

The code does not crash with a `NameError`

## Environment

This is not easily recoverable.  While it's possible, I believe that the description above points to the root cause pretty clearly.

**Comment by danthe3rd** [comment]
Hi,
How did you install xformers? It looks like you didn't build the library

**Comment by swails** [comment]
If you install from conda using the following environment.yaml file:

```yaml
name: xformers-test
channels:
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/xformers
  - https://conda.anaconda.org/dglteam/label/cu117
  - https://conda.anaconda.org/nvidia
  - https://conda.anaconda.org/conda-forge

dependencies:
  - python>=3.10
  - pip

  - pytorch >=2.0.0,<3.0.0a
  - pytorch-cuda==11.7
  - xformers==0.0.25

  - dgl ==1.1.0.cu117
  - torchmetrics >=0.10.0,<1.0.0a
  - pytorch-lightning >=1.7.3,<1.9.0
```

Then it installs xformers alongside a non-CUDA enabled PyTorch library and xformers is installed without the C++/CUDA libraries installed, straight from the xformers conda channel.

That said, the way the code is written it *looks* like the intent was to "work" in some fashion even without the C++ library available, but there are isinstance checks that break when this is the case.

Note that easing the pin on pytorch-cuda (so it's simply `>=11.7,<12.0a`) seems to resolve the issue (in that PyTorch is built with the CUDA bindings and xformers has the C++ library available).

That said, I think it would be worth clarifying the requirements in this package and, at a minimum, throw a more useful exception if the C++ library is actually required rather than an obscure NameError.
