### ISSUE TITLE
Can't pickle with xformers after 81bc427

### ISSUE THREAD

**Issue by jramapuram** [facebookresearch/xformers#203]
# 🐛 Bug

I'm running into pickling errors after commit https://github.com/facebookresearch/xformers/commit/81bc427fa5cd8feca5babef0d9ebe649170c83ac

Pickling is needed for some DDP contexts.

## Pseudocode

```python
import pickle

class ViTB(nn.Module):
    def __init__(self):
        super().__init__()
        self.xformer = xFormer.from_config(xFormerConfig([self.model_config]))  # eg: Generic ViT-B conf

pickle.dumps(ViTB())

```

I haven't bisected, but on head (https://github.com/facebookresearch/xformers/commit/093224ec9c5486c7dc163b73532ced1c8a30b5e7 at this time) this results in:
```bash
AttributeError: Can't pickle local object '_init_from_params.<locals>.init_method'
```

## Expected behavior

Model pickles correctly (needed for certain DDP contexts).

## Environment

- PyTorch Version (e.g., 1.0): 1.10.2 (tried earlier versions, same issue). 
- OS (e.g., Linux): Ubuntu 20.04
- How you installed PyTorch (`conda`, `pip`, source): conda

**Comment by blefaudeux** [comment]
oh, thanks for the report, this is unexpected ! (and the repro will make a perfect unit test so that this does not appear again)

**Comment by blefaudeux** [comment]
ah, could be related to the FusedMLP which pulls in Triton, this would at least make sense with respect to the linked commit. Just in case, is triton installed on your machine ?

**Comment by blefaudeux** [comment]
> ```shell
> _init_from_params
> ```

replying to myself: nope, this is not because of fusedMLP, I can repro indeed. Fixing that

**Comment by jramapuram** [comment]
You beat me to it :). Let me know if you need anything else.

**Comment by jramapuram** [comment]
Here is my config if helpful (it is pretty vanilla):

```yaml
reversible: False
block_type: "encoder"
num_layers: 12
dim_model: 768
layer_norm_style: "pre"

multi_head_config:
  num_heads: 12
  residual_dropout: 0.1
  use_rotary_embeddings: true

  attention:
    name: "scaled_dot_product"
    dropout: 0.0
    causal: False

feedforward_config:
  name: "MLP"
  dropout: 0.0
  activation: "gelu"
  hidden_layer_multiplier: 4

```
